service: multifamilyCalc

provider:
  name: aws
  runtime: nodejs8.10

functions:
  calc:
    handler: handler.calc
    events:
      - http:
          path: /calculate
          method: get
          cors: true